### ISSUE TITLE
Undeclared dependency on requests

### ISSUE THREAD

**Issue by jdemeyer** [UniFormal/mmt_jupyter_kernel#3]
```
Traceback (most recent call last):
  File "/usr/local/src/sage-config/local/lib/python3.8/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/src/sage-config/local/lib/python3.8/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/tmp/mmt_jupyter_kernel/mmt_kernel/__init__.py", line 5, in <module>
    from .kernel import MMTKernel
  File "/tmp/mmt_jupyter_kernel/mmt_kernel/kernel.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

**Comment by kaiamann** [comment]
Have you installed the `requests` module? If not, install it with `pip install requests`.

**Comment by jdemeyer** [comment]
> Have you installed the `requests` module?

No, I have not.

**Comment by tkw1536** [comment]
@kaiamann you should add a requirements.txt file.
